linters:
  enable-all: true
  disable:
    - varnamelen
    - paralleltest
    - lll
    - exhaustruct
    - ireturn
    - forcetypeassert
    - wsl
    - funlen
    - wastedassign
    - rowserrcheck
    - wrapcheck
    - gochecknoglobals
    - gci
    - testifylint
    - err113
    - mirror
    - revive
    - depguard
    - recvcheck
    - perfsprint
    - exportloopref