name: Unit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Install make
      run: sudo apt-get install make -y

    - name: Configure Terraform
      run: |
        # This replaces the $HOME variable with the appropriate value.
        envsubst < .terraformrc_template > ~/.terraformrc

    - name: Install tools
      run: make tools

    - name: Build
      run: make

    - name: Generate
      run: make generate

    - name: Run gencheck
      run: make gencheck

    - name: Run lint
      run: make lint

    - name: Run unit tests
      run: make unit

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3